### ISSUE TITLE
Component disabling on save of a .object file

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-scenestaging#2]
Components are disabling themselves while saving a object file after editing values or adding a extra component as shown in the video below. ( Project is the most recent version as of creating this Issue ) 

https://github.com/Facepunch/sbox-scenestaging/assets/40073828/cfa5608f-67a9-4cc3-9521-49bfdda1f8cb

**Comment by garrynewman** [comment]
I can't repro this - are you getting any errors in the console during this?

**Comment by B0zy** [comment]
None, It seems only to happen once I've been working on the project for more then a hour. That usually when it starts to happen again

**Comment by B0zy** [comment]
I'm getting the issue again with the only thing put in console is Detected Asset File Change and this is the inspector code from it

> [GameMenu] Detected Asset File Changed /player.object_c
   at Sandbox.ResourceLoader.OnAssetFileChanged(String file, GameResourceAttribute type)
   at Sandbox.ResourceLoader.OnAssetFilesChanged(FileWatch watch, GameResourceAttribute type)
   at Sandbox.ResourceLoader.<>c__DisplayClass3_0.<AddWatcherForType>b__0(FileWatch w)
   at Sandbox.FileWatch.TriggerCallback(List`1 value)
   at Sandbox.FileWatch.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 108
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58

**Comment by DrakeFruit** [comment]
been having this issue too kinda? pressing ctrl + s sometimes disables the component I interacted with most recently. clicking out of the inspector tab usually fixes it

**Comment by garrynewman** [comment]
Is this fixed now?

**Comment by B0zy** [comment]
Seems to have been fixed yes, thank you.
