### ISSUE TITLE
Referencing components on the root object in a prefab causes errors

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-scenestaging#66]
https://github.com/Facepunch/sbox-scenestaging/assets/7847372/47a26abd-1e5d-4099-ae2d-3cd387fa789e

Code for the component looks like this:
```CS
public class DamageProxy : BaseComponent, IDamageable
{
	[Property]
	public ActorComponent DamageableProxy { get; set; }


	public bool CauseHitBounce { get; set; }
	public bool PlayHitSound { get; set; }

	public void TakeDamage( DamageEventData data )
	{
		DamageableProxy.TakeDamage( data );
	}
}
```

When I referenced components on objects other than the root, it seemed to work fine.

**Comment by chrisspieler** [comment]
Here's a prefab that repros this issue using just AnimatedModelComponent and CitizenAnimation components:
[repro.zip](https://github.com/Facepunch/sbox-scenestaging/files/13392058/repro.zip)

**Comment by garrynewman** [comment]
What are the errors?

**Comment by Fortune117** [comment]
I get a million errors like this:
![image](https://github.com/Facepunch/sbox-scenestaging/assets/7847372/3eba6c8c-3ba5-44b6-b29f-2d19b9cb37e7)

```
Error calling event 'tool.frame' on 'EditorScene'
System.NullReferenceException: Object reference not set to an instance of an object.
   at BaseComponent.<>c__DisplayClass6_2.<DeserializeProperty>b__1() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\Components\BaseComponent.Serialize.cs:line 127
   at BaseComponent.PostDeserialize() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\Components\BaseComponent.cs:line 110
   at GameObject.PostDeserialize() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\GameObject\GameObject.Serialize.cs:line 188
   at SceneUtility.<>c__DisplayClass7_0.<DeferInitializationScope>b__0() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\SceneUtility.cs:line 128
   at Sandbox.Utility.DisposeAction.Dispose()
   at EditorScene.UpdatePrefabsInScene(Scene scene, PrefabFile prefab) in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 235
   at EditorScene.UpdatePrefabInstances(PrefabScene scene, PrefabFile prefab) in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 250
   at PrefabEditorSession.OnEdited() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\PrefabEditorSession.cs:line 20
   at SceneEditorSession.ProcessSceneEdits() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\SceneEditorSession.cs:line 128
   at SceneEditorSession.Tick() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\SceneEditorSession.cs:line 116
   at EditorScene.SceneEditorTick() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 144
   at InvokeStub_EditorScene.SceneEditorTick(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

```

```
GameObject - c76549ce-6f23-4278-80cd-f61b4fcd8255 was not found for ActorComponent.Body
   at BaseComponent.<>c__DisplayClass6_2.<DeserializeProperty>b__1() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\Components\BaseComponent.Serialize.cs:line 125
   at BaseComponent.PostDeserialize() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\Components\BaseComponent.cs:line 110
   at GameObject.PostDeserialize() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\GameObject\GameObject.Serialize.cs:line 188
   at SceneUtility.<>c__DisplayClass7_0.<DeferInitializationScope>b__0() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\GameEngine\SceneUtility.cs:line 128
   at Sandbox.Utility.DisposeAction.Dispose()
   at EditorScene.UpdatePrefabsInScene(Scene scene, PrefabFile prefab) in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 221
   at EditorScene.UpdatePrefabInstances(PrefabScene scene, PrefabFile prefab) in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 250
   at PrefabEditorSession.OnEdited() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\PrefabEditorSession.cs:line 20
   at SceneEditorSession.ProcessSceneEdits() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\SceneEditorSession.cs:line 128
   at SceneEditorSession.Tick() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\Session\SceneEditorSession.cs:line 116
   at EditorScene.SceneEditorTick() in C:\My Stuff\Steam\steamapps\common\sbox\addons\sbox-scenestaging\code\Editor\EditorScene.cs:line 144
   at InvokeStub_EditorScene.SceneEditorTick(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass11_0.<BuildDelegate>b__0(Object o, Object[] p)
   at Sandbox.Internal.EventSystem.Run(String v)
   at Editor.EditorEvent.Run(String name)
   at Editor.ManagedTools.RunFrame()
   at Managed.SourceTools.Exports.Editor_ManagedTools_RunFrame()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 108
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
```

**Comment by FancyApricot** [comment]
root never gets added to a Scene.Directory because it is a PrefabScene : Scene

```csharp
GameObjectDirectory.cs

internal void Add( GameObject go, Guid previouslyKnownAs )
{
	// if ( go is Scene ) return;
	if ( go is Scene && go is not PrefabScene ) return;
```
